version: "3.12"

services:
  postgres:
    image: postgres
    container_name: postgres_chaos
    restart: always
    ports:
      - "5431:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345678
      POSTGRES_DB: ChaosEngineering
    volumes:
      - pgdata:/var/lib/postgresql/data

  fastapi:
    build: .
    container_name: fastapi_chaos
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    environment:
      DATABASE_URL: "postgresql://postgres:12345678@postgres:5432/ChaosEngineering"

volumes:
  pgdata: