"""changes in models name --> product

Revision ID: 4ef8bb4f5d17
Revises: a80c3239a25f
Create Date: 2025-09-28 09:08:41.854872

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ef8bb4f5d17'
down_revision: Union[str, Sequence[str], None] = 'a80c3239a25f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('product', sa.String(), nullable=False))
    op.alter_column('items', 'description',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('items', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.alter_column('items', 'description',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('items', 'product')
    # ### end Alembic commands ###
