"""debugging status

Revision ID: 75e095dc312d
Revises: 1b4a47f58330
Create Date: 2025-09-28 09:57:01.224361

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75e095dc312d'
down_revision: Union[str, Sequence[str], None] = '1b4a47f58330'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('statuses', sa.Column('type', sa.Enum('await_confirmation', 'confirmed', 'in_delivery', 'delivered', 'canceled', name='statustype'), nullable=False))
    op.drop_column('statuses', 'status')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('statuses', sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('statuses', 'type')
    # ### end Alembic commands ###
