"""changes in model

Revision ID: a64cb8b6b5f9
Revises: 4ef8bb4f5d17
Create Date: 2025-09-28 09:29:25.767016

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a64cb8b6b5f9'
down_revision: Union[str, Sequence[str], None] = '4ef8bb4f5d17'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('statuses', sa.Column('status', sa.Enum('await_confirmation', 'confirmed', 'in_delivery', 'delivered', 'canceled', name='statustype'), nullable=False))
    op.drop_column('statuses', 'type')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('statuses', sa.Column('type', postgresql.ENUM('await_confirmation', 'confirmed', 'in_delivery', 'delivered', 'canceled', name='statustype'), autoincrement=False, nullable=False))
    op.drop_column('statuses', 'status')
    # ### end Alembic commands ###
