"""debugging status

Revision ID: c3105883593e
Revises: a64cb8b6b5f9
Create Date: 2025-09-28 09:43:15.793285

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c3105883593e'
down_revision: Union[str, Sequence[str], None] = 'a64cb8b6b5f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('statuses', 'status',
               existing_type=postgresql.ENUM('await_confirmation', 'confirmed', 'in_delivery', 'delivered', 'canceled', name='statustype'),
               type_=sa.String(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('statuses', 'status',
               existing_type=sa.String(),
               type_=postgresql.ENUM('await_confirmation', 'confirmed', 'in_delivery', 'delivered', 'canceled', name='statustype'),
               existing_nullable=False)
    # ### end Alembic commands ###
